DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS persons;

CREATE TABLE IF NOT EXISTS persons
(
    id       bigint generated by default as identity,
    name     varchar(250)        not null,
    email    varchar(254) unique not null,
    password varchar(254)        not null,
    role     varchar(254)        not null,
    CONSTRAINT persons_pk PRIMARY KEY (id),
    CONSTRAINT name_min_length CHECK (char_length(name) >= 2),
    CONSTRAINT email_min_length CHECK (char_length(email) >= 6)
);

CREATE TABLE IF NOT EXISTS events
(
    id           bigint generated by default as identity,
    author_id    bigint       not null,
    title        varchar(250) not null,
    description  text         not null,
    start_time   timestamp    not null,
    created_time timestamp    not null,
    rating       bigint default (0),
    CONSTRAINT events_pk PRIMARY KEY (id),
    CONSTRAINT author_pk FOREIGN KEY (author_id) REFERENCES persons (id)
);