-- DROP TABLE IF EXISTS persons;

CREATE TABLE IF NOT EXISTS persons
(
    id       bigint generated by default as identity,
    name     varchar(250)        not null,
    email    varchar(254) unique not null,
    password varchar(254)        not null,
    CONSTRAINT persons_pk PRIMARY KEY (id),
    CONSTRAINT name_min_length CHECK (char_length(name) >= 2),
    CONSTRAINT email_min_length CHECK (char_length(email) >= 6)
);